language: node_js
node_js:
- lts/*
notifications:
  email: false
cache: yarn
stages:
  - test
  - pages
  - release
jobs:
  include:
    - stage: test
      script: npm run build
    - stage: pages
      script: 
        - npm run clean
        - npm run typedoc
      deploy:
        provider: pages
        local_dir: docs
        skip-cleanup: true
        github-token: "$GH_TOKEN"
        keep-history: true
        verbose: true
        on:
          branch: master
    - stage: release
      script:
        - npm run clean
        - npm run buildUpdate
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: sziklaszlo@gmail.com
        skip_cleanup: true
        api_key:
          secure: I0Q2bjJ6LNUkx7qtp3mDOh9SdGRM6F1aF6MH+LOf69DMDZ0CxTXnvSJQ3jn8k+7F5FgDdHGbK7qZmn4Q6HFoQQ90cg4t2FwCNGktdC3sgBHP0eOiOqOS9YsqjD6lDKmhJij+JbUN8uTNMZoHbOVmtubhOY8q8JdOLPBQhHviP5zYheYr4EVfjro9CDDcRxAjNXO5XJYPAZSpGwinYSmWuxaa8MTK8gVC4s69nuBH5p45nlWyvEhc0aEBwbBlElReaOGdswJcNEgiPffFXu1fvO/xv3N0lM7ScTwM6zcG1y7FBjOwHnHP0NzTdR8ElKqQTNwxnxgCyXmK3/HUGf8DV+BxVSrjhLAAzc/H21Kb0VKWGeayvksAKrhd+uvVPcpx7k67g+QyBfRRjn5IXTtoQI4Q+/4UyvKUpp+dR7B7vHjvNBtmX77aiVAvZ+qAoUU7UdKd5i5CSn2bksETlNQ2Zjx9guffg9K+tlkhxiZc8sLVQIzWJgY96DFLMdOZm+xCUL8WkKu+t6j1riVge0TrJJXYnvLnsl+qMP46Tp3zPWlpJu6MI2hWOCjf8JP9g+H4IRIiHpxxGgT7zjCZYxf4BBlqZ2aQlXt7T+YEwEa+78XKxgejOAOcm7NOE26m+LaAeJFBwyLEQVfzr6iq4eipoOF+yKGqmyQxXvZPlVz0IgU=
        on:
          branch: master
          tags: true