name: CI
on:
  push:
    branches:
      - main
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
  workflow_dispatch:
jobs:
  call_npm_package_build:
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    uses: szikszail/workflows/.github/workflows/npm-package-build.yml@v1
