name: Docs
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  call_typedocs_pages:
    permissions:
      contents: write
    uses: szikszail/workflows/.github/workflows/typedocs-pages.yml@v1
