name: Investigation
on:
  workflow_dispatch:
jobs:
  build_and_test:
    name: Build and test NPM package
    strategy:
      matrix:
        os: [windows-latest]
        node-version: [lts/-1, lts/*, latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Info
        run: node -e "console.log('CWD', process.cwd())"
      - name: Checkout
        uses: actions/checkout@v3
      - name: RMDIR
        run: |
          node -e "const fs = require('fs'); (fs.rmSync ? fs.rmSync : fs.rmdirSync)(process.cwd() + '\\tests\\cli\\data\\destination', { recursive: true });"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Build and test
        run: npm run build