# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull requests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - name: Monitor coverage
        if: ${{ always() }}
        uses: szikszail/coverage-monitor-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "coverage/clover.xml"
          threshold_alert: 60
          threshold_warning: 80
          threshold_metric: "branches"